### ISSUE TITLE
Show user profile on Hover

### ISSUE THREAD

**Issue by thamaraiselvam** [Hashnode/user-feedback#92]
Showing user profile on hover would save a lot of time, Something like this

![download](https://user-images.githubusercontent.com/6559664/59324597-2b257380-8cfd-11e9-906f-2f5ddbf3d765.png)

**Comment by minecrawler** [comment]
Hashnode already has profiles on hover, however they are not implemented consistently. Where exactly are you missing one?

![](https://cdn.hashnode.com/res/hashnode/image/upload/v1560323901484/MllbPyCuD.png)

**Comment by BolajiAyodeji** [comment]
Hi @thamaraiselvam, thanks for this feedback.

This issue is live already, please check again.

**Comment by minecrawler** [comment]
It's not live everywhere. For example, on my following page, when hovering users, there is no popup at all! When hovering the avatar of a user in my notifications, for example when they liked my post, I neither get any popup. Imho, it's there, scattered all over the place, sometimes, if I am lucky, but in general, it's a bad (non-existent) experience.

**Comment by BolajiAyodeji** [comment]
Hi @minecrawler, 

There isn't supposed to be a popup on your following page as the profile card shows some details about the user already. Hovering the avatar of a user in notifications works already.

I just checked and somehow it doesn't work when it's a like or comment notification. Kindly report this in a new issue and we'll take it up.

Profile popups on hover are live everywhere except the followers/following pages, which is intentional. Please check again and let me know if you have any more questions or concerns. Cheers!
